config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get '/about' => 'pages#about', as: :about

  resources :posts, only: [:new, :create, :edit, :update, :show, :index, :destroy]

end

app/models/application_record.rb
# # can't find table ``

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# create_table :posts, force: :cascade do |t|
#   t.string :title
#   t.text :body
#   t.datetime :created_at, null: false
#   t.datetime :updated_at, null: false
#   t.integer :user_id
#   t.text :meta_description
#   t.string :slug
#   t.index [:slug], name: :index_posts_on_slug, unique: true
# end

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

end

app/models/user.rb
# create_table :users, force: :cascade do |t|
#   t.string :email, default: "", null: false
#   t.string :encrypted_password, default: "", null: false
#   t.string :reset_password_token
#   t.datetime :reset_password_sent_at
#   t.datetime :remember_created_at
#   t.integer :sign_in_count, default: 0, null: false
#   t.datetime :current_sign_in_at
#   t.datetime :last_sign_in_at
#   t.inet :current_sign_in_ip
#   t.inet :last_sign_in_ip
#   t.datetime :created_at, null: false
#   t.datetime :updated_at, null: false
#   t.integer :role
#   t.index [:email], name: :index_users_on_email, unique: true
#   t.index [:reset_password_token], name: :index_users_on_reset_password_token, unique: true
# end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  enum role: [:reader, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def meta_title(title)
    [title, BRAND_NAME].reject(&:empty?).join(' | ')
  end
  
  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @meta_title = meta_title 'About'
    @meta_description = 'What is Kaizen and how can it be applied to Ruby on Rails and other development platforms as well as incorporated into life in general.'
  end

  def home
    @posts = Post.all.order(created_at: :desc).limit(3)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
    @meta_title = meta_title 'Learning Rails One Small Step at a Time'
    @meta_description = 'Applying the Kaizen method of small steps to learning Ruby on Rails, Javascript, and more!'
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Post Created Successfully!'
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = 'Post Updated Successfully!'
      redirect_to root_url
    else
      render :edit
    end
  end

  def show
    @meta_title = meta_title @post.title
    @meta_description = @post.meta_description
  end

  def destroy
    @post.destroy
    flash[:notice] = "#{@post.title} Deleted"
    redirect_to posts_path
  end

  private

  def get_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :meta_description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashes.html.haml
.flashes
  - if notice 
    .alert.alert-success.alert-dismissible.fade.show
      %button{ type: 'button', class: 'close', 'data-dismiss' => "alert", 'aria-label' => "Close" }
        %span{ 'aria-hidden' => 'true' } &times;
      %p= notice
  - if alert 
    .alert.alert-danger.alert-dismissible.fade.show
      %button{ type: 'button', class: 'close', 'data-dismiss' => "alert", 'aria-label' => "Close" }
        %span{ 'aria-hidden' => 'true' } &times;
      %p= alert

app/views/layouts/_footer.html.haml
%footer

app/views/layouts/_header.html.haml
!!!
%html
  %head
    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-107249930-1', 'auto');

    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= @meta_title ? @meta_title : ApplicationController::BRAND_NAME
    - if @meta_description.present?
      %meta{ name: 'description', content: "#{@meta_description}" }
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_nav.html.haml
%ul.nav.justify-content-center
  %li.nav-item
    = link_to 'Home', root_url, class: 'nav-link'
  %li.nav-item
    = link_to 'About', about_path, class: 'nav-link'
  %li.nav-item
    = link_to 'Blog', posts_path, class: 'nav-link'
  - if current_user.nil?
    %li.nav-item
      = link_to 'Sign in', new_user_session_path, class: 'nav-link'
  - else
    %li.nav-item
      = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/layouts/application.html.haml
= render partial: 'layouts/header'

%body
  = render partial: 'layouts/nav'
  = render partial: 'layouts/flashes'
  .container-fluid
    = yield

  = render partial: 'layouts/footer'

app/views/layouts/devise.html.haml
= render partial: 'layouts/header'

.container-fluid
  = yield

app/views/pages/about.html.haml
%h1 About Kaizen Rails

.card
  .card-body
    %p Kaizen is a Japanese term that literally means 'Change for better.' This humble word, however, has become a philosophy and practice with far greater reach and impact than a mere dictionary would suggest. Kaizen has been implemented in manufacturing, software development, business, and other industries since it's development shortly after World War II. At the heart of Kaizen is its focus on continuous improvement through large or small, one-time or continuous actions.

    %p Rails is a server-side web application framework built using the Ruby programming language and is known for it's ability to generate web applications very quickly.

    %p KaizenRails is my journey to learn web development one step at a time. Utilizing the Ruby on Rails framework, I plan on learning (and maybe helping a few others on the way) to build my very own web application. I've attempted this before, but often failed because of the large scope of the project. With the help of Kaizen, I hope to take this journey one step at a time. I have no goals other than to make one small change a day. Join me as I embark on this journey. 

app/views/pages/home.html.haml
.site-header
  .site-name.col-3
    %h1 Kaizen
    %h1 Rails
  - if @posts.any?
    .latest_post.col-5
      .card
        .card-header
          %h4
            = @posts.first.title
            %small.em= time_ago_in_words(@posts.first.created_at)
        .card-body
          %p= @posts.first.body
  .social-media-icons
   
    %a{ href: '//www.instagram.com', target: 'blank', rel: 'nofollow' }
      %i.fa.fa-instagram
    %a{ href: FACEBOOK_URL, target: 'blank', rel: 'nofollow' }
      %i.fa.fa-facebook-square
    %a{ href: '//www.twitter.com', target: 'blank', rel: 'nofollow' }
      %i.fa.fa-twitter-square
.container

  - if @posts.any?
    - @posts.each do |post|
      = render post, locals: { post: post }

app/views/posts/_form.html.haml
.col-12
  = form_for @post do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :body
      = f.text_area :body, class: 'form-control large-textarea'

    .form-group
      = f.label :meta_description
      = f.text_area :meta_description, class: 'form-control'


    = submit_tag button_title, class: 'btn btn-sm btn-outline-light'

app/views/posts/_post.html.haml
.card
  .card-header
    %h1= link_to post.title, post_path(post)
    %small
      = time_ago_in_words(post.created_at)
      ago
      by
      = post&.user&.email || 'anonymous'
  .card-body
    %p= post.body
  - if current_user&.admin?
    .card-footer
      = link_to 'Edit', edit_post_path(post) 
      = link_to "Delete", post, class: 'cancel-link', method: :delete

app/views/posts/edit.html.haml
= render partial: 'form', locals: { post: @post, button_title: 'Save' }

app/views/posts/index.html.haml
- if current_user&.admin?  
  = link_to 'Add Post', new_post_path, class: 'btn btn-sm btn-light' if !current_user.nil?

= render @posts

app/views/posts/new.html.haml
= render partial: 'form', locals: { post: @post, button_title: 'Create'}

app/views/posts/show.html.haml
= render @post

app/views/users/shared/_links.html.haml
.row.justify-content-center
  - if controller_name != 'sessions'
    .devise-link= link_to "Log in", new_session_path(resource_name)
  - if devise_mapping.registerable? && controller_name != 'registrations'
    .devise-link= link_to "Sign up", new_registration_path(resource_name)
  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    .devise-link= link_to "Forgot your password?", new_password_path(resource_name)
  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    .devise-link= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    .devise-link= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      .devise-link= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)